brew: Install OpenJDK before attempting Clojure
I got this exception without it:

    clojure: Java 1.8+ is required to install this formula.
    Install AdoptOpenJDK with Homebrew Cask:
      brew cask install adoptopenjdk
    Error: An unsatisfied requirement failed this build.
    Installing clojure has failed!